[project]
name = "Church-Link"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiosqlite>=0.21.0",
    "fastapi>=0.115.11",
    "firebase-admin>=6.7.0",
    "pydantic>=2.10.6",
    "motor>=3.7.0",
    "python-dotenv>=1.0.1",
    "scalar-fastapi>=1.0.3",
    "uvicorn>=0.34.0",
]
