import { AccountPermissions } from "@/types/AccountPermissions";

//I asked chatgpt to give me a bunch of test data to play with

export const MockPermData: AccountPermissions[] = [
    {
        name: "Administrator",
        isAdmin: true,
        manageWholeSite: true,
        editAllEvents: true,
        editAllPages: true,
        accessFinances: true,
        manageNotifications: true,
        manageMediaContent: true,
        manageUserPermissions: true,
        manageBiblePlan: true,
    },
    {
        name: "Youth Ministry",
        isAdmin: false,
        manageWholeSite: false,
        editAllEvents: false,
        editAllPages: false,
        accessFinances: false,
        manageNotifications: false,
        manageMediaContent: true,
        manageUserPermissions: false,
        manageBiblePlan: false,
    },
    {
        name: "Moderator",
        isAdmin: false,
        manageWholeSite: false,
        editAllEvents: true,
        editAllPages: true,
        accessFinances: true,
        manageNotifications: true,
        manageMediaContent: true,
        manageUserPermissions: true,
        manageBiblePlan: true,
    },
    {
        name: "Guest Speaker",
        isAdmin: false,
        manageWholeSite: false,
        editAllEvents: false,
        editAllPages: false,
        accessFinances: false,
        manageNotifications: false,
        manageMediaContent: false,
        manageUserPermissions: false,
        manageBiblePlan: false,
    },
    {
        name: "Tech Support",
        isAdmin: false,
        manageWholeSite: false,
        editAllEvents: false,
        editAllPages: false,
        accessFinances: false,
        manageNotifications: false,
        manageMediaContent: true,
        manageUserPermissions: false,
        manageBiblePlan: false,
    },
    {
        name: "Finance Manager",
        isAdmin: false,
        manageWholeSite: false,
        editAllEvents: false,
        editAllPages: false,
        accessFinances: true,
        manageNotifications: false,
        manageMediaContent: false,
        manageUserPermissions: false,
        manageBiblePlan: false,
    },
    {
        name: "Sunday School Teacher",
        isAdmin: false,
        manageWholeSite: false,
        editAllEvents: true,
        editAllPages: false,
        accessFinances: false,
        manageNotifications: false,
        manageMediaContent: false,
        manageUserPermissions: false,
        manageBiblePlan: true,
    },
    {
        name: "Event Coordinator",
        isAdmin: false,
        manageWholeSite: false,
        editAllEvents: true,
        editAllPages: true,
        accessFinances: false,
        manageNotifications: true,
        manageMediaContent: false,
        manageUserPermissions: false,
        manageBiblePlan: false,
    },
    {
        name: "Livestream Moderator",
        isAdmin: false,
        manageWholeSite: false,
        editAllEvents: false,
        editAllPages: false,
        accessFinances: false,
        manageNotifications: true,
        manageMediaContent: true,
        manageUserPermissions: false,
        manageBiblePlan: false,
    },
    {
        name: "Deacon",
        isAdmin: false,
        manageWholeSite: false,
        editAllEvents: true,
        editAllPages: true,
        accessFinances: true,
        manageNotifications: true,
        manageMediaContent: false,
        manageUserPermissions: true,
        manageBiblePlan: true,
    },
    {
        name: "Volunteer",
        isAdmin: false,
        manageWholeSite: false,
        editAllEvents: false,
        editAllPages: false,
        accessFinances: false,
        manageNotifications: false,
        manageMediaContent: false,
        manageUserPermissions: false,
        manageBiblePlan: false,
    },
    {
        name: "Music Director",
        isAdmin: false,
        manageWholeSite: false,
        editAllEvents: false,
        editAllPages: false,
        accessFinances: false,
        manageNotifications: true,
        manageMediaContent: true,
        manageUserPermissions: false,
        manageBiblePlan: false,
    },
    {
        name: "Outreach Coordinator",
        isAdmin: false,
        manageWholeSite: false,
        editAllEvents: true,
        editAllPages: false,
        accessFinances: false,
        manageNotifications: true,
        manageMediaContent: false,
        manageUserPermissions: false,
        manageBiblePlan: true,
    },
    {
        name: "Hospitality Team",
        isAdmin: false,
        manageWholeSite: false,
        editAllEvents: false,
        editAllPages: false,
        accessFinances: false,
        manageNotifications: false,
        manageMediaContent: false,
        manageUserPermissions: false,
        manageBiblePlan: false,
    },
    {
        name: "Security Team",
        isAdmin: false,
        manageWholeSite: true,
        editAllEvents: false,
        editAllPages: false,
        accessFinances: false,
        manageNotifications: false,
        manageMediaContent: false,
        manageUserPermissions: false,
        manageBiblePlan: false,
    },
    {
        name: "Prayer Warrior",
        isAdmin: false,
        manageWholeSite: false,
        editAllEvents: false,
        editAllPages: false,
        accessFinances: false,
        manageNotifications: false,
        manageMediaContent: false,
        manageUserPermissions: false,
        manageBiblePlan: true,
    },
    {
        name: "Small Group Leader",
        isAdmin: false,
        manageWholeSite: false,
        editAllEvents: true,
        editAllPages: false,
        accessFinances: false,
        manageNotifications: true,
        manageMediaContent: false,
        manageUserPermissions: false,
        manageBiblePlan: true,
    },
    {
        name: "Administrative Assistant",
        isAdmin: false,
        manageWholeSite: false,
        editAllEvents: false,
        editAllPages: true,
        accessFinances: false,
        manageNotifications: true,
        manageMediaContent: false,
        manageUserPermissions: false,
        manageBiblePlan: false,
    },
    {
        name: "Board Member",
        isAdmin: true,
        manageWholeSite: true,
        editAllEvents: true,
        editAllPages: true,
        accessFinances: true,
        manageNotifications: true,
        manageMediaContent: true,
        manageUserPermissions: true,
        manageBiblePlan: true,
    },
    {
        name: "Guest",
        isAdmin: false,
        manageWholeSite: false,
        editAllEvents: false,
        editAllPages: false,
        accessFinances: false,
        manageNotifications: false,
        manageMediaContent: false,
        manageUserPermissions: false,
        manageBiblePlan: false,
    },
    {
        name: "Missions Director",
        isAdmin: false,
        manageWholeSite: false,
        editAllEvents: true,
        editAllPages: true,
        accessFinances: false,
        manageNotifications: true,
        manageMediaContent: false,
        manageUserPermissions: false,
        manageBiblePlan: true,
    },
];
