import { UserInfo } from "@/types/UserInfo";

export const MockUserData: UserInfo[] = [
    {
        firstName: "John",
        lastName: "Doe",
        email: "johndoe@example.com",
        dateOfBirth: new Date("1990-02-15"),
        permissions: ["Administrator", "Moderator"],
    },
    {
        firstName: "Jane",
        lastName: "Smith",
        email: "janesmith@example.com",
        dateOfBirth: new Date("1985-11-22"),
        permissions: [],
    },
    {
        firstName: "Alice",
        lastName: "Johnson",
        email: "alice.johnson@example.com",
        dateOfBirth: new Date("1992-04-01"),
        permissions: ["Music Director"],
    },
    {
        firstName: "Bob",
        lastName: "Brown",
        email: "bobbrown@example.com",
        dateOfBirth: new Date("1978-07-25"),
        permissions: ["Deacon", "Volunteer"],
    },
    {
        firstName: "Charlie",
        lastName: "Davis",
        email: "charliedavis@example.com",
        dateOfBirth: new Date("1983-09-10"),
        permissions: ["Event Coordinator"],
    },
    {
        firstName: "Debbie",
        lastName: "Martinez",
        email: "debbie.martinez@example.com",
        dateOfBirth: new Date("1994-12-05"),
        permissions: ["Finance Manager", "Youth Ministry"],
    },
    {
        firstName: "George",
        lastName: "Miller",
        email: "george.miller@example.com",
        dateOfBirth: new Date("1987-03-18"),
        permissions: [],
    },
    {
        firstName: "Hannah",
        lastName: "Wilson",
        email: "hannah.wilson@example.com",
        dateOfBirth: new Date("1995-05-30"),
        permissions: ["Tech Support", "Event Coordinator"],
    },
    {
        firstName: "Isaac",
        lastName: "Moore",
        email: "isaac.moore@example.com",
        dateOfBirth: new Date("1998-01-12"),
        permissions: [],
    },
    {
        firstName: "Lily",
        lastName: "Taylor",
        email: "lily.taylor@example.com",
        dateOfBirth: new Date("1991-06-20"),
        permissions: ["Prayer Warrior"],
    },
    {
        firstName: "Mia",
        lastName: "Anderson",
        email: "mia.anderson@example.com",
        dateOfBirth: new Date("1980-09-09"),
        permissions: ["Administrator"],
    },
    {
        firstName: "Noah",
        lastName: "Thomas",
        email: "noah.thomas@example.com",
        dateOfBirth: new Date("1982-11-02"),
        permissions: ["Livestream Moderator", "Moderator"],
    },
    {
        firstName: "Olivia",
        lastName: "Jackson",
        email: "olivia.jackson@example.com",
        dateOfBirth: new Date("1997-02-17"),
        permissions: ["Outreach Coordinator"],
    },
    {
        firstName: "Parker",
        lastName: "White",
        email: "parker.white@example.com",
        dateOfBirth: new Date("1986-08-11"),
        permissions: ["Small Group Leader", "Volunteer"],
    },
    {
        firstName: "Quincy",
        lastName: "Harris",
        email: "quincy.harris@example.com",
        dateOfBirth: new Date("1990-03-21"),
        permissions: [],
    },
    {
        firstName: "Riley",
        lastName: "Clark",
        email: "riley.clark@example.com",
        dateOfBirth: new Date("1993-07-14"),
        permissions: ["Security Team", "Deacon"],
    },
    {
        firstName: "Sophia",
        lastName: "Lewis",
        email: "sophia.lewis@example.com",
        dateOfBirth: new Date("1989-01-29"),
        permissions: ["Guest"],
    },
    {
        firstName: "Tyler",
        lastName: "Young",
        email: "tyler.young@example.com",
        dateOfBirth: new Date("1984-04-10"),
        permissions: ["Administrative Assistant", "Event Coordinator"],
    },
    {
        firstName: "Ursula",
        lastName: "King",
        email: "ursula.king@example.com",
        dateOfBirth: new Date("1991-05-24"),
        permissions: ["Tech Support"],
    },
    {
        firstName: "Victor",
        lastName: "Scott",
        email: "victor.scott@example.com",
        dateOfBirth: new Date("1996-10-02"),
        permissions: ["Administrator", "Board Member"],
    },
    {
        firstName: "Wendy",
        lastName: "Green",
        email: "wendy.green@example.com",
        dateOfBirth: new Date("1992-12-01"),
        permissions: [],
    },
    {
        firstName: "Xander",
        lastName: "Adams",
        email: "xander.adams@example.com",
        dateOfBirth: new Date("1994-03-06"),
        permissions: ["Board Member"],
    },
    {
        firstName: "Yvonne",
        lastName: "Baker",
        email: "yvonne.baker@example.com",
        dateOfBirth: new Date("1988-09-13"),
        permissions: ["Music Director", "Youth Ministry"],
    },
    {
        firstName: "Zachary",
        lastName: "Gonzalez",
        email: "zachary.gonzalez@example.com",
        dateOfBirth: new Date("1980-07-22"),
        permissions: ["Outreach Coordinator"],
    },
    {
        firstName: "Amelia",
        lastName: "Carter",
        email: "amelia.carter@example.com",
        dateOfBirth: new Date("1982-06-18"),
        permissions: ["Event Coordinator", "Deacon"],
    },
    {
        firstName: "Benjamin",
        lastName: "Mitchell",
        email: "benjamin.mitchell@example.com",
        dateOfBirth: new Date("1991-04-27"),
        permissions: ["Moderator", "Youth Ministry"],
    },
    {
        firstName: "Chloe",
        lastName: "Rodriguez",
        email: "chloe.rodriguez@example.com",
        dateOfBirth: new Date("1987-09-15"),
        permissions: ["Livestream Moderator"],
    },
    {
        firstName: "Daniel",
        lastName: "Perez",
        email: "daniel.perez@example.com",
        dateOfBirth: new Date("1995-12-02"),
        permissions: ["Volunteer", "Missions Director"],
    },
    {
        firstName: "Eva",
        lastName: "Murphy",
        email: "eva.murphy@example.com",
        dateOfBirth: new Date("1993-08-19"),
        permissions: ["Board Member", "Administrator"],
    },
    {
        firstName: "Felix",
        lastName: "Graham",
        email: "felix.graham@example.com",
        dateOfBirth: new Date("1989-10-13"),
        permissions: [],
    },
    {
        firstName: "Grace",
        lastName: "Wright",
        email: "grace.wright@example.com",
        dateOfBirth: new Date("1984-03-29"),
        permissions: ["Tech Support", "Music Director"],
    },
    {
        firstName: "Henry",
        lastName: "King",
        email: "henry.king@example.com",
        dateOfBirth: new Date("1990-02-01"),
        permissions: ["Deacon"],
    },
    {
        firstName: "Ivy",
        lastName: "Hernandez",
        email: "ivy.hernandez@example.com",
        dateOfBirth: new Date("1996-04-22"),
        permissions: ["Youth Ministry", "Prayer Warrior"],
    },
    {
        firstName: "Jack",
        lastName: "Lopez",
        email: "jack.lopez@example.com",
        dateOfBirth: new Date("1992-06-11"),
        permissions: ["Guest", "Small Group Leader"],
    },
    {
        firstName: "Katherine",
        lastName: "Garcia",
        email: "katherine.garcia@example.com",
        dateOfBirth: new Date("1985-01-28"),
        permissions: ["Board Member", "Administrator", "Manage User Permissions"],
    },
    {
        firstName: "Liam",
        lastName: "Evans",
        email: "liam.evans@example.com",
        dateOfBirth: new Date("1997-07-09"),
        permissions: ["Event Coordinator"],
    },
    {
        firstName: "Megan",
        lastName: "Nelson",
        email: "megan.nelson@example.com",
        dateOfBirth: new Date("1994-05-16"),
        permissions: ["Security Team"],
    },
    {
        firstName: "Nathan",
        lastName: "Thomas",
        email: "nathan.thomas@example.com",
        dateOfBirth: new Date("1993-02-21"),
        permissions: ["Outreach Coordinator", "Event Coordinator"],
    },
    {
        firstName: "Olivia",
        lastName: "Moore",
        email: "olivia.moore@example.com",
        dateOfBirth: new Date("1987-09-30"),
        permissions: ["Tech Support"],
    },
    {
        firstName: "Paul",
        lastName: "Martinez",
        email: "paul.martinez@example.com",
        dateOfBirth: new Date("1988-11-15"),
        permissions: ["Volunteer"],
    },
    {
        firstName: "Quinn",
        lastName: "Roberts",
        email: "quinn.roberts@example.com",
        dateOfBirth: new Date("1990-10-19"),
        permissions: ["Music Director"],
    },
    {
        firstName: "Rosa",
        lastName: "Collins",
        email: "rosa.collins@example.com",
        dateOfBirth: new Date("1984-12-08"),
        permissions: ["Moderator", "Administrator"],
    },
    {
        firstName: "Samuel",
        lastName: "Walker",
        email: "samuel.walker@example.com",
        dateOfBirth: new Date("1995-08-26"),
        permissions: ["Administrator"],
    },
    {
        firstName: "Tina",
        lastName: "Young",
        email: "tina.young@example.com",
        dateOfBirth: new Date("1993-01-10"),
        permissions: ["Deacon", "Board Member"],
    },
    {
        firstName: "Ursula",
        lastName: "Bennett",
        email: "ursula.bennett@example.com",
        dateOfBirth: new Date("1996-03-07"),
        permissions: ["Prayer Warrior", "Tech Support"],
    },
    {
        firstName: "Vera",
        lastName: "Mitchell",
        email: "vera.mitchell@example.com",
        dateOfBirth: new Date("1986-04-04"),
        permissions: ["Youth Ministry", "Deacon"],
    },
    {
        firstName: "William",
        lastName: "Parker",
        email: "william.parker@example.com",
        dateOfBirth: new Date("1982-02-16"),
        permissions: ["Moderator"],
    },
    {
        firstName: "Xena",
        lastName: "Taylor",
        email: "xena.taylor@example.com",
        dateOfBirth: new Date("1992-09-29"),
        permissions: ["Administrator", "Event Coordinator"],
    },
    {
        firstName: "Yasmine",
        lastName: "Johnson",
        email: "yasmine.johnson@example.com",
        dateOfBirth: new Date("1987-05-11"),
        permissions: ["Music Director", "Tech Support"],
    },
    {
        firstName: "Zane",
        lastName: "Carter",
        email: "zane.carter@example.com",
        dateOfBirth: new Date("1989-08-03"),
        permissions: ["Volunteer", "Security Team"],
    },
];
